### ISSUE TITLE
Typo in source code?

### ISSUE THREAD

**Issue by wiku30** [koide3/hdl_graph_slam#73]
In hdl_graph_slam/apps/hdl_graph_slam_nodelet.cpp, Line 103, the topic name "/velodyne_poits" should be "/velodyne_points". I wonder how it still works with the typo.
By the way, I wish that the topic names can be more flexible (e.g. in launch files) than hard-coded. For example, I have been trying to use it with rslidar sensors, and IMU/GPS with other frame/topic names. It could have been more convenient than looking at example dataset/source code and find the exact topic names that I should remap to.

**Comment by koide3** [comment]
Hi @wiku30 ,
Since the topic name is immediately overwritten by the rosparam named "points_topic", it didn't affect the program. Anyways, I fixed the typo. Thank you for reporting it :)

Regarding the topic names, you can take a look at the descriptions in README which tells you topics you can use in this package. 
https://github.com/koide3/hdl_graph_slam#constraints-edges

**Comment by wiku30** [comment]
Thanks@
