### ISSUE TITLE
[pcl::NormalEstimation::compute] input_ is empty!

### ISSUE THREAD

**Issue by facontidavide** [koide3/hdl_graph_slam#84]
Hi,

I am trying outdoor mapping with my rosbag (rslidar) and  hdl_graph_slam_400.launch

I of course remapped the rslidar_point message, but I get the following message:

                  [pcl::NormalEstimation::compute] input_ is empty!

Any clue? Do you want me to share the rosbag to reproduce the error?

**Comment by sintax2con** [comment]
unable to detect the floor， maybe too few points after prefilterring 
check the prefilterring nodelet

**Comment by facontidavide** [comment]
I am using a 16 rays Robosense laser and the field of view is limited to +/- 110 degrees.

I guess I can edit the parameter **floor_pts_thresh** accordingly.

If I can make a suggestion, it would be nice if the error message is a little more informative :)

**Comment by facontidavide** [comment]
For the record, it worked. Mapping is ok-ish, whilst localization is a bit off, but this is another problem.

**Comment by ipinyulun** [comment]
hi @facontidavide 
what did u edit to have it works?
i try to decrese and increase floor_pts_thresh but its not working

**Comment by arjunskumar** [comment]
@ipinyulun are you able to solve this?

**Comment by Yu1107** [comment]
* in hdl_graph_slam/apps/floor_detection_nodelet.cpp
  ```
    // too few points for RANSAC
    if(filtered->size() < floor_pts_thresh) {
      std::cout << "filtered: " << filtered->size() << std::endl;
      return boost::none;
    }
  ```
filtered->size() always 0 so input_ is empty!

and changing "enable_floor_detection" in your launch file to "false"

**Comment by arjunskumar** [comment]
@Yu1107 thanks, I was able to work in our small office environment.

**Comment by ElFloco** [comment]
@Yu1107 you are right, the array is always empty, because if you have a sensor height greater than `height_clip_range`, then the floor is not considered

I edited following line in `floor_detection_nodelet.cpp:`
`filtered = plane_clip(filtered, Eigen::Vector4f(0.0f, 0.0f, 1.0f, sensor_height - height_clip_range), true);`

to:
`filtered = plane_clip(filtered, Eigen::Vector4f(0.0f, 0.0f, 1.0f, -height_clip_range), true);`

So points below are considered aswell. Now the floor detection works.
