### ISSUE TITLE
How to lower the weight to GPS data?

### ISSUE THREAD

**Issue by wiku30** [koide3/hdl_graph_slam#85]
I have run a rosbag in which the GPS data (especially altitude) is not very accurate. For that data, I found that if the GPS is disabled, the map is accurate, but if it is enabled, the map is corrupted.
So I wonder how can I lower the confidence of GPS data, or disable the information of altitude(for example).

**Comment by koide3** [comment]
Hi @wiku30 ,
There are two parameters which determine the weight of GPS data ("gps_edge_stddev_(xy|z)"). You can give them a large value to lower the GPS weight. If you want to completely disable only the altitude data, you can replace the input altitude data with NaN, then the system makes 2D constraints instead of 3D.

https://github.com/koide3/hdl_graph_slam/blob/d8dad34fc2a63d0d4e32bce7e61c5fb378d6eb7a/launch/hdl_graph_slam.launch#L108
https://github.com/koide3/hdl_graph_slam/blob/d8dad34fc2a63d0d4e32bce7e61c5fb378d6eb7a/launch/hdl_graph_slam.launch#L109
https://github.com/koide3/hdl_graph_slam#constraints-edges
